GCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('Aluno/', include('Aluno.urls')),
    path('Coordenador/', include('coordenador.urls')),
    path('user/', include('Users.urls')),
    path('user/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coordenador/urls.py
from django.urls import path
from Aluno.views import password_change
from .views import  home_professor,\
                    lista_aproveitamento,\
                    lista_certificacao_professor,\
                    lista_certificacao,\
                    aproveitamento,\
                    certificacao,\
                    iniciar_periodo_disciplina,\
                    iniciar_periodo_de_certificacao_listagem_disciplinas,\
                    search_aproveitamento,\
                    search_certificacao
urlpatterns = [
    
    path('home_coordenador/', home_professor, name='sweet-home_teacher'),
    path('lista_disciplinas_iniciar_certificacao/<int:curso_id>', iniciar_periodo_de_certificacao_listagem_disciplinas, name='iniciar_certificacao'),
    path('Iniciar_periodo_de_requisicao/<int:disciplina_id>', iniciar_periodo_disciplina, name='iniciar_periodo'),
    path('lista_aproveitamento/', lista_aproveitamento, name='aproveitamento_list'),
    path('lista_certificacao/professor/<int:id>', lista_certificacao_professor, name='certificacao_list_professor'),
    path('lista_certificacao/', lista_certificacao, name='certificacao_list'),
    path('lista_aproveitamento/<int:aproveitamento_id>', aproveitamento, name='aproveitamento'),
    path('lista_certificacao/<int:certificacao_id>', certificacao, name='certificacao'),
    path('professor_home/alterar_senha/',  password_change.as_view(), name = 'teacher_change_password'),

    path('lista_aproveitamento/ajax/<str:text>', search_aproveitamento, name = 'ajax-aproveitamento'),
    path('lista_certificacao/ajax/<str:text>', search_certificacao, name = 'ajax-certificacao'),
]

Aluno/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.

class Aproveitamento_de_disciplina (models.Model):
    
    STATUS = (
        ("aprovado", "Aprovado"),
        ("reprovado", "Reprovado"),
        ("aguardo", "Aguardo")
    )

    disciplina =  models.ForeignKey('administrador.Disciplina', on_delete=models.CASCADE)
    motivo = models.CharField("Motivo", max_length=250, blank=True, null=True)
    
    historico = models.FileField(("Historico"), upload_to='documentos', max_length=1000)
    ementa = models.FileField(("Ementa antiga escola"), upload_to='documentos', max_length=1000)
    ementa_atual = models.FileField(("Ementa nova escola"), upload_to='documentos', max_length=1000)
    comprovante = models.FileField(("Comprovante"), upload_to='documentos', max_length=1000, blank=True, null=True)
    
    status_requisição = models.CharField(("Status"), choices=STATUS, blank=False, null=False, max_length=20,  default='reprovado')
    requisitor =  models.ForeignKey(User, verbose_name=("Requisitor"), on_delete=models.CASCADE, blank=False, null=False)
 
    verbose_name = 'Aproveitamento de disciplina'
    verbose_name_plural = 'Aproveitamentos de disciplina'
    
    class Meta:
      db_table = 'Aluno_aproveitamento_de_disciplina'
      unique_together = (('disciplina', 'requisitor'),)
    
    def __str__(self):
        return self.disciplina.nome +' '+ self.requisitor.username
    
    
    
class Certificação_de_conhecimento (models.Model):
    
    STATUS = (
        ("aprovado", "Aprovado"),
        ("reprovado", "Reprovado"),
        ("aguardo", "Aguardo")
    )

    disciplina =  models.ForeignKey('administrador.Disciplina', on_delete=models.CASCADE)
    status_requisição = models.CharField(("Status"), choices=STATUS, blank=False, null=False, max_length=20,  default='reprovado')
    nota = models.FloatField(("Nota"), blank=True, null=True, default=0)
    requisitor =  models.ForeignKey(User, verbose_name=("Requisitor"), on_delete=models.CASCADE, blank=False, null=False)

    verbose_name = 'Certificação de conhecimento'
    verbose_name_plural = 'Certificações de conhecimento'
    
    class Meta:
      db_table = 'Aluno_certificação_de_conhecimento'
      unique_together = (('requisitor', 'disciplina'),)
    
    def __str__(self):
        return self.disciplina.nome +' '+ self.requisitor.username
    
    

administrador/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Disciplina (models.Model):

    OPTATIVA = (
        ("S", "Sim"),
        ("N", "Não"),
    )
    
    STATUS = (
        ("Cursando", "Cursando"),
        ("Aprovado", "Aprovado"),
        ("Espera", "Espera")
    )
    
    nome = models.CharField(("Nome da Disciplina"), max_length=150, null=False)
    perido = models.IntegerField(("Periodo da disciplina"))
    carga_horaria = models.IntegerField(("Carga Horaria"))
    optativa = models.CharField(("Opitativa"), choices=OPTATIVA, blank=False, null=False,max_length=20)
    dependencia = models.ManyToManyField("self", verbose_name=("Dependencias"), blank=True, default='Sem Dependencia')
    aberto = models.BooleanField(("Aberto"), default='False')
    status = models.CharField('Status', choices=STATUS, max_length=20, default="Cursando")
    data_final = models.DateField(("Data Final"), blank=True, null=True,auto_now=False, auto_now_add=False)
    
    pedagogo = models.ForeignKey (User, verbose_name=("pedagogo"), on_delete=models.CASCADE, related_name='pedagogo', blank=True, null=True)
    banca_de_professores = models.ManyToManyField(User, verbose_name=("Banca de professores"), related_name='professores', blank=True, null=True)
    
    verbose_name = 'Disciplina'
    verbose_name_plural = 'Disciplinas'
    
    def __str__(self):
        return self.nome +' '+ str(self.perido) 
    
class Curso (models.Model):
    
    nome = models.CharField(("Nome do Curso"), max_length=150, null=False, blank=False)
    ano = models.DateField("Ano")
    periodos =  models.IntegerField(('Total de peridodos'), null=False, blank=False)
    #periodo_atual = models.IntegerField(('Total de peridodos'), null=True, blank=True)
    disciplina = models.ManyToManyField("administrador.Disciplina", verbose_name=("Disciplinas"),blank=False)
    
    coordenador = models.ForeignKey(User, verbose_name=("Coordenador"), on_delete=models.SET_NULL, null=True)
    
    
    verbose_name = 'Curso'
    verbose_name_plural = 'Cursos'
    
    def __str__(self):
        return self.nome +' ('+ str(self.ano.year) +')'
    

coordenador/models.py
from django.db import models

# Create your models here.

coordenador/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import PasswordChangeView 
from django.urls import reverse, reverse_lazy
from Users.forms import CustomUserCreateForm,  CustomUserChangeForm,  PasswordChangeForm
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.urls import reverse
from administrador.models import Curso, Disciplina
from Aluno.models import Aproveitamento_de_disciplina, Certificação_de_conhecimento
from django.contrib.auth import get_user_model
from Aluno.form import Form_aproveitamento_de_disciplina, Form_certificação_de_conhecimento
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from datetime import date

from .form import Form_disciplina_iniciar_perido_de_certificacao



User = get_user_model()

# Create your views here.

@login_required(login_url='/user/login/')
def home_professor (request):
    
    try:
        
        if request.user.primeiro_login == True:
        
            primeiro_login = redirect ('/Coordenador/professor_home/alterar_senha/', {})
            return primeiro_login
        
        coordenador = True
        professor = User.objects.get(id=request.user.id)
        professor_curso_name = professor.curso_relacao
        professor_curso_disciplinas = professor.curso_relacao.disciplina.all()
        requisicoes_de_aproveitamento = Aproveitamento_de_disciplina.objects.all()
        requisicoes_de_certificacao = Certificação_de_conhecimento.objects.all()

        print('coordenador de', professor_curso_name)
        lista_de_disciplinas_curso = set()
        aluno = []
        aluno_do_curso = set()
        aluno_do_disciplina = set()

        for dados in requisicoes_de_aproveitamento:
            print(dados, dados.disciplina.id,  dados.requisitor, '<<')
            if professor_curso_name == dados.requisitor.curso_relacao:
                print(dados, dados.disciplina.id,  dados.requisitor,  dados.requisitor.disciplina_relacao, '<<' 'acho')
                aluno_do_curso.add(dados.requisitor)

        for disciplnas in professor_curso_disciplinas.all():
            print(disciplnas, disciplnas.id, '<')
            lista_de_disciplinas_curso.add(disciplnas.id)


        for dados in aluno_do_curso:
            print(dados, ',,,,,')

        requisicoes_de_aproveitamento = Aproveitamento_de_disciplina.objects.filter (Q(requisitor__in = aluno_do_curso))
        
        requisicoes_de_certificacao = Certificação_de_conhecimento.objects.all()

        print('coordenador de', professor_curso_name)
        lista_de_disciplinas_curso = set()
        aluno = []
        aluno_do_curso = set()
        aluno_do_disciplina = set()

        for dados in requisicoes_de_certificacao:
            print(dados, dados.disciplina.id,  dados.requisitor, '<<')
            if professor_curso_name == dados.requisitor.curso_relacao:
                print(dados, dados.disciplina.id,  dados.requisitor,  dados.requisitor.disciplina_relacao, '<<' 'acho')
                aluno_do_curso.add(dados.requisitor)

        for disciplnas in professor_curso_disciplinas.all():
            print(disciplnas, disciplnas.id, '<')
            lista_de_disciplinas_curso.add(disciplnas.id)


        for dados in aluno_do_curso:
            print(dados, ',,,,,')

        requisicoes_de_certificacao = Certificação_de_conhecimento.objects.filter (Q(requisitor__in = aluno_do_curso))

        usuario = request.user
        print(usuario.curso_relacao.id, '<<<')
        
        teacher_group = Group.objects.get(name='Professor')
        
        teste =  professor.disciplina_relacao.all()
        
        for disciplinas in teste:
            for professor in disciplinas.banca_de_professores.all():
                print(professor.id, professor.username, 'user-', request.user.id)
                if professor.id == request.user.id:
                    print('GG')
        
        
        print(teste, '<')
        
        ###fix vvv
        
        banca_user = set()
        banca_disciplina = set()
        
        user = User.objects.get(id=request.user.id)
        disciplinas  = Disciplina.objects.all()
        
        for disciplina in disciplinas:
            print(disciplina.banca_de_professores.all())
            for professor in disciplina.banca_de_professores.all():
                print(professor.id,  professor.username)
                if professor.id == user.id:
                    print('GG')
                    banca_user.add(professor)
                    banca_disciplina.add(disciplina)
                    
        #fix
                  
        print(banca_disciplina, 'aaaaaaaaa')
            
        msg = 'Você não é Coordenador :p'
        teacher_group = Group.objects.get(name='Professor')
        certificacao = Certificação_de_conhecimento.objects.all()
        print(certificacao)
        
        for certificacoes in certificacao:
            print(certificacoes.disciplina, certificacoes.disciplina.banca_de_professores.all())
            for professor in certificacoes.disciplina.banca_de_professores.all():
                if professor.username == request.user.username:
                    print('GG  aq')
        
        
        return render(request, 'home_professor.html', { 'total_aproveitamentos': len(requisicoes_de_aproveitamento),
                                                        'aproveitamento': requisicoes_de_aproveitamento,
                                                        'total_certificacao' : len (requisicoes_de_certificacao),
                                                        'certificacao' : requisicoes_de_certificacao,
                                                        'coordenador': coordenador,
                                                        'usuario':usuario,
                                                        'Professor': teacher_group,
                                                        'disciplinas' : disciplinas,
                                                        'banca':banca_user,
                                                        'banca_disciplina':banca_disciplina,
                                                        'certificacao':certificacao})
    except:
        
        banca_user = set()
        banca_disciplina = set()
        
        user = User.objects.get(id=request.user.id)
        disciplinas  = Disciplina.objects.all()
        
        for disciplina in disciplinas:
            print(disciplina.banca_de_professores.all())
            for professor in disciplina.banca_de_professores.all():
                print(professor.id,  professor.username)
                if professor.id == user.id:
                    print('GG')
                    banca_user.add(professor)
                    banca_disciplina.add(disciplina)
                    
        print(banca_disciplina, 'aaaaaaaaa')
            
        coordenador = False
        msg = 'Você não é Coordenador :p'
        teacher_group = Group.objects.get(name='Professor')
        certificacao = Certificação_de_conhecimento.objects.all()
        print(certificacao)
        
        for certificacoes in certificacao:
            print(certificacoes.disciplina, certificacoes.disciplina.banca_de_professores.all())
            for professor in certificacoes.disciplina.banca_de_professores.all():
                if professor.username == request.user.username:
                    print('GG  aq')
            
        
        
        
        return render(request, 'home_professor.html', {'coordenador': coordenador,
                                                       'msg': msg,
                                                       'Professor': teacher_group,
                                                       'disciplinas' : disciplinas,
                                                       'banca':banca_user,
                                                       'banca_disciplina':banca_disciplina,
                                                       'certificacao':certificacao}) 

@login_required(login_url='/user/login/')
def iniciar_periodo_de_certificacao_listagem_disciplinas(request, curso_id):

    aluno = request.user

    #curso = Curso.objects.all()
    curso  = Curso.objects.get(id=curso_id)
    m2m  = curso.disciplina.all()
    len_disciplinas = len(curso.disciplina.all())
    
    len_optativas = 0
    len_nao_opttivas = 0
    
    for disciplina in m2m:
        if disciplina.optativa == 'S':
            len_optativas  +=1
        else:
            len_nao_opttivas += 1
    
    return  render (request, 'periodo_de_certificacao_listagem.html', {'curso': curso,
                                                       'disciplinas' : m2m,
                                                       'total_disciplinas' : len_disciplinas,
                                                       'total_de_optativas': len_optativas,
                                                       'total_de_nao_optativas' : len_nao_opttivas})
    
    return  render(request, 'periodo_de_certificacao_listagem.html', {})

@login_required(login_url='/user/login/')
def lista_certificacao_professor (request, id):
    
    disciplina = Disciplina.objects.get(id=id)
    certificacao = Certificação_de_conhecimento.objects.all()
    certificacao_id = set()
    
    for certificacoes in certificacao:
        print(certificacoes.disciplina, certificacoes.disciplina.banca_de_professores.all())
        if certificacoes.disciplina.id == id:
            print(certificacoes.disciplina.id, certificacoes.requisitor, '<<<')
            certificacao_id.add(certificacoes)
            
    print(certificacao_id, '<<<<<<<<')
    
    return  render(request, 'certificacao_lista_professor.html', {'certificacoes':certificacao_id,

coordenador/templates/aproveitamento.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/aproveitamento.css' %}">
<title>Aproveitamento</title>

{% endblock %}

{% block main %}
<div class="main">
    <div class="dados">
        <p class="titulo text_color_white">
            Requisição de Aproveitamento de Disciplina
        </p>
        <div style="color: red;">{{ form.errors }}</div>
        <div class="content">
            <img class="img_user" src="{{ aproveitamento.requisitor.image.url }}" width="200px" height="200px" alt="">

            <div class="text_data text_color_white">
                <div class="text_content">
                    <p>Nome:</p>
                    <p>{{aproveitamento.requisitor}}</p>
                </div>
                <div class="text_content">
                    <p>Matricula:</p>
                    <p>{{aproveitamento.requisitor.matricula}}</p>
                </div>
                <div class="text_content">
                    <p>Disciplina:</p>
                    <p>{{aproveitamento.disciplina}}</p>
                </div>
                <div class="text_content">
                    <p>Motivo:</p>
                    <p>{{aproveitamento.motivo}}</p>
                </div>
                <div class="text_content">
                    <div class="documentos">
                        <p>Documentos:</p>
                        <a href="{{aproveitamento.historico.url}}" download>
                            <p>Historico</p>
                        </a>
                        <a href="{{aproveitamento.ementa.url}}" download>
                            <p>Ementa Passada</p>
                        </a>
                        <a href="{{aproveitamento.ementa_atual.url}}" download>
                            <p>Ementa Atual</p>
                        </a>
                        <a href="{{aproveitamento.comprovante.url}}" download>
                            <p>Comprovante</p>
                        </a>
                        
                    </div>
                </div>
        

            </div>

        </div>

        <form class="teste" method="post" action="{% url 'aproveitamento' aproveitamento.id %}">
            {%csrf_token%}
            <div style="visibility: hidden; position:absolute">
                {{form.disciplina}}
                {{form.motivo}}
                {{form.historico}}
                {{form.comprovante}}
                {{form.requisitor}}
            </div>

            <select name="status_requisição"  onchange="this.form.submit()" id="id_status_requisição" multiple>

                <option class="reprovar" value="reprovado">Reprovar</option>
                <option class="aprovar"  value="aprovado">Aprovar</option>
                
              
            </select>

        </form>

    </div>
</div>
{% endblock %}

coordenador/templates/certificacao.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/certificacao.css' %}">
<title>Certificacao</title>

{% endblock %}

{% block main %}
<div class="main">
    <form class="teste" method="post" action="{% url 'certificacao' certificacao.id %}">
        {%csrf_token%}
        <div class="dados">
            <p class="titulo text_color_white">
                Requisição de Certificacao de Disciplina
            </p>
            <div style="color: red;">{{ form.errors }}</div>
            <div class="content">
                <img class="img_user" src="{{ certificacao.requisitor.image.url }}" width="200px" height="200px" alt="">
            
                <div class="text_data text_color_white">
                    <div class="text_content">
                        <p>Nome:</p>
                        <p>{{certificacao.requisitor}}</p>
                    </div>
                    <div class="text_content">
                        <p>Matricula:</p>
                        <p>{{certificacao.requisitor.matricula}}</p>
                    </div>
                    <div class="text_content">
                        <p>Disciplina:</p>
                        <p>{{certificacao.disciplina}}</p>
                    </div>
              
                    <div class="text_content">
                        <p>Nota:</p>
                        <div>{{form.nota}}</div>
                    </div>

                    <div class="text_content">
                        <p>banca:</p>
                        <div>{{form.banca_de_professores}}</div>
                    </div>

                    <div class="text_content">
                        <p>Pedagogo:</p>
                        <div>{{form.pedagogo}}</div>
                    </div>
                </div>
            
            </div>
        
        
                <div style="visibility: hidden; position:absolute">
                    {{form.disciplina}}
                    {{form.motivo}}
                    {{form.historico}}
                    {{form.comprovante}}
                    {{form.requisitor}}
                </div>
            
                <select name="status_requisição"  onchange="this.form.submit()" id="id_status_requisição" multiple>
                
                    <option class="reprovar" value="reprovado">Remover Nota</option>
                    <option class="aprovar"  value="aprovado">inserir Nota</option>
                    
                </select>
        </div>
    </form>
</div>
{% endblock %}

coordenador/templates/certificacao_lista_professor.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/lista_aproveitamento.css' %}">
<title>Lista de Certificações</title>

{% endblock %}

{% block main %}
<div class="main">

    <div class="main">

        <p class="title">Requisicoes de Certificacao de Conhecimento da Disciplina {{disciplina.nome}}</p>
    
        <div class="center">
            
            <div class="two_lables">
                <div>
                    <p class="label_title">Requisicoes</p>

                    <p class="label_title"></p>
                
                </div>
        
            </div>
    
        </div>
    
    
        <div class="center_2">
    
            <div class="list">
                
                <table class="table" >
                    <thead>
                      <tr>
                        <th scope="col">id</th>
                        <th scope="col">Requisitor</th>
                        <th scope="col">Disciplina</th>
                        <th class="top_side_fourth" scope="col">Nota</th>
                        <th class="top_side_fifth" scope="col">-</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for dados in certificacoes %}
                            {% if dados.status_requisição == 'aprovado' %}
                                <tr style="background-color: #9cff9c;">
                                
                                    <th scope="row"> {{dados.id}} </th>
                                    <td>{{dados.requisitor}}</td>
                                    <td>{{dados.disciplina}}</td>
                                    <td class="center_tabl_">{{dados.nota}}</td>
                                    <td class="center_table">
                                        <a>
                                        
                                            -
                                        
                                        </a>
                                    </td>

                                </tr>
                            {% else %}

                                <tr>
                                    
                                    <th scope="row"> {{dados.id}} </th>
                                    <td>{{dados.requisitor}}</td>
                                    <td>{{dados.disciplina}}</td>
                                    <td class="center_tabl_">{{dados.nota}}</td>
                                    <td class="center_table">
                                        <a href="{% url 'certificacao' dados.id %}">
                                        
                                            <button>
                                                Visualizar
                                            </button>
                                        
                                        </a>
                                    </td>
                                
                                </tr>
                            
                            {% endif %}
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
    
    
        </div>
     
    </div>

</div>
{% endblock %}

coordenador/templates/iniciar_periodo_disciplina.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/iniciar_certificacao.css' %}">
<title>Iniciar Periodo {{disciplina.nome}}</title>

{% endblock %}

{% block main %}

{{ form.errors }}

<p class="white title">{{disciplina.nome}}</p>
<form action=""  method="POST">
    {%csrf_token%}
    <div class="form_disciplina">

        <div class="dados">
            <p class="white"> Perido da Disciplina: {{form.perido.value}} </p>
            <p class="white"> Carga Horaria: {{form.carga_horaria.value}}</p>
            {% if form.optativa.value == 'S' %}
                <p class="white"> Optativa: SIM</p>
            {% elif form.optativa.value == 'N' %}
                <p class="white"> Optativa: NÃO</p>
            {% endif %}

            {%  if form.aberto.value == False %}
                <p class="white">Status Para requsição de aproveitamento de disciplina: Fechado</p>
            {% elif form.aberto.value == True %}
                <p class="white">Status Para requsição de aproveitamento de disciplina: Aberto</p>
            {% endif %}
            
            {% if form.data_final.value != None %}
                <p class="white" style="pointer-events: none; touch-action: none; ">Data para a Finalização das requisições de certificação de conhecimento: {{form.data_final}}</p>
                
                <div class="banca">
                    <p class="white">Professores que compoem a banca:</p>
                    <!-- {{form.banca_de_professores}} -->
                    <select style="pointer-events: none; touch-action: none; " name="banca_de_professores" required="" id="id_banca_de_professores" multiple="">
                        
                        {% for professor in disciplina.banca_de_professores.all %}
                            <option value="{{professor.id}}">{{professor.username}}</option>
                        {% endfor %}
                      </select>
                </div>

                <div class="pedagogo">
                    <p class="white" style="pointer-events: none; touch-action: none; ">Pedagogo:  </p>
                    <p class="white" >{{disciplina.pedagogo.username}}</p>
                </div>

                <p class="white_" >A data final para as requisições de certificações de conhecimento para a disciplina de {{disciplina.nome}} é {{disciplina.data_final}}</p>
            {% else %}
                <p class="white">Digite uma data para a Finalização das requisições de certificação de conhecimento: {{form.data_final}}</p>

                              
                <div class="banca">
                    <p class="white">Selecione os professores para compor a banca:</p>
                    <!-- {{form.banca_de_professores}} -->
                    <select name="banca_de_professores" required="" id="id_banca_de_professores" required multiple="">
                        
                        {% for professor in professores%}
                            <option value="{{professor.id}}">{{professor.username}}</option>
                        {% endfor %}
                      </select>
                </div>

                <div class="pedagogo">
                    <p class="white">Selecione um pedagogo:  </p>
                    {{form.pedagogo}}
                </div>

            {% endif %}

            

            
        </div>

        <div class="dependencias">
            <p class="white title_dependencias">Dependencias:</p>

            <div class="lista_das_dependencias">
                {% for disciplinas in dependencias.all %}
                    <p class="white">{{disciplinas.nome}}</p>
                {% endfor %}
            </div>
        </div>

    </div>

    {% if form.data_final.value != None %}
       
    {% else %}
        <button class="star_chain">
            <input type="submit" value='Iniciar Certificação de conhecimento'>
        </button>
    {% endif %}

    <!-- {{form.as_p}} -->

    <div class="display_hidden"  >
        {{form.nome}}
        {{form.perido}}
        {{form.carga_horaria}}
        {{form.optativa}}
        {{form.dependencia}}
    </div>

</form>
{% endblock %}