GCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('Aluno/', include('Aluno.urls')),
    path('Coordenador/', include('coordenador.urls')),
    path('user/', include('Users.urls')),
    path('user/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrador/urls.py
from django.contrib import admin
from django.urls import path
from .views import  home_view,\
                    sign_up_course_view,\
                    sign_up_subject_view,\
                    register_coordinator_view,\
                    teste_view,\
                    SignUpView_Student,\
                    SignUpView_Teacher,\
                    lista_cursos,\
                    lista_Disciplinas,\
                    lista_Aluno,\
                    lista_Professors,\
                    diciplina_especifica,\
                    aluno_especifico,\
                    professor_especifico,\
                    curso_especifico,\
                    search_aluno,\
                    search_professor,\
                    search_curso,\
                    search_disciplina,\
                    CONFIG

urlpatterns = [

    path('',  home_view, name = 'home'),

    path('adm/sigh_up_student/cadastro_Estudante/', SignUpView_Student.as_view(), name='cadastro_estudante'),
    path('adm/sigh_up_student/cadastro_Professor/', SignUpView_Teacher.as_view(), name='cadastro_professor'),

    path('adm/sigh_up_course',  sign_up_course_view, name = 'sign_up_course'),
    path('adm/sigh_up_subject',  sign_up_subject_view, name = 'sign_up_subject'),
    path('adm/register_coordinator',  register_coordinator_view, name = 'register_coordinator'),
    
    path('adm/list_courses/',  lista_cursos, name = 'lista_cursos'),
    path('adm/list_subjects/',  lista_Disciplinas, name = 'lista_disciplinas'),
    path('adm/list_students/',  lista_Aluno, name = 'lista_Aluno'),
    path('adm/list_coordinator/',  lista_Professors, name = 'lista_professor'),
    
    path('adm/disciplina/<int:id>', diciplina_especifica, name = 'disciplina'),
    path('adm/aluno/<int:id>', aluno_especifico, name = 'aluno'),
    path('adm/professor/<int:id>', professor_especifico, name = 'professor'),
    path('adm/curso/<int:id>', curso_especifico, name = 'curso'),
    path('adm/professor/<int:id>', professor_especifico, name = 'professor'),
    
    path('adm/list_students_ajax/<str:text>', search_aluno, name='ajax_lista_aluno' ),
    path('adm/list_teacher_ajax/<str:text>', search_professor, name='ajax_lista_professor' ),
    path('adm/list_course_ajax/<str:text>', search_curso, name='ajax_lista_curso' ),
    path('adm/list_subject_ajax/<str:text>', search_disciplina, name='ajax_lista_disciplina' ),
    
    path('CONFIG/<int:id>', CONFIG, name = 'CONFIG'),
    path('adm/teste',  teste_view, name = 'teste'),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.db.models import signals

# Create your models here.

class UserManager(BaseUserManager):
    #REQUIRED_FIELDS = ['matricula','username' , 'email' ,'cpf', 'phone']

    def _create_user(self, image,  matricula, username, email, cpf,  phone, data_de_nascimento, disciplina_relacao, password, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        if not matricula:
           raise ValueError("O matricula é obrigatório")
        if not username:
           raise ValueError("O username é obrigatório")
        if not cpf:
           raise ValueError("O cpf é obrigatório")
        if not phone:
            raise ValueError("O phone é obrigatório")
        
        email = self.normalize_email(email)
        
        """ username = seusername
        matricula = seemail """
        
        user = self.model(image=image, matricula=matricula, username=username, email=email, cpf=cpf, phone=phone, data_de_nascimento=data_de_nascimento, disciplina_relacao=disciplina_relacao, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def _create_super_user(self,  matricula, username, email, cpf,  phone, password, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        if not matricula:
           raise ValueError("O matricula é obrigatório")
        if not username:
           raise ValueError("O username é obrigatório")
        if not cpf:
           raise ValueError("O cpf é obrigatório")
        if not phone:
            raise ValueError("O phone é obrigatório")
        
        email = self.normalize_email(email)
        
        """ username = seusername
        matricula = seemail """
        
        user = self.model(matricula=matricula, username=username, email=email, cpf=cpf, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, image, matricula, username, email, cpf,  phone, data_de_nascimento=None, disciplina_relacao=None,password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', True)
        return self._create_user( image, matricula, username, email, cpf,  phone, data_de_nascimento, disciplina_relacao, password, **extra_fields)

    def create_superuser(self, matricula, username, email, cpf, phone, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser = True')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff = True')

        return self._create_super_user( matricula, username, email, cpf,  phone, password, **extra_fields)



class CustomUser(AbstractUser):


    image = models.ImageField(upload_to='Media', blank=True, null=False, default='Media/no_image_dafaut.jpg')
    matricula = models.CharField("Matricula", max_length=150, unique=True)
    username = models.CharField(("Nome"), max_length=50, unique=False, primary_key=None)
    email = models.EmailField("E-mail", unique=True)
    cpf = models.CharField("CPF", max_length=14, unique=True)
    phone = models.CharField("Telefone", max_length=15, blank=True, null=True)
    data_de_nascimento = models.DateField('Data de Nascimento', blank=True, null=True)
    primeiro_login = models.BooleanField(default=True)
    
    
    curso_relacao = models.ForeignKey("administrador.Curso", verbose_name=("Curso"), blank=True, null=True,on_delete=models.SET_NULL)
    disciplina_relacao = models.ManyToManyField("administrador.Disciplina", verbose_name=("Disciplina"), blank=True)
    
    disciplina_concluidas = models.ManyToManyField("administrador.Disciplina", related_name='Disciplina_cluidas', verbose_name=("Disciplina Concluidas"), blank=True)
    
    is_staff = models.BooleanField('Membro da equipe', default=True)

    USERNAME_FIELD = 'matricula'
    REQUIRED_FIELDS = ['username' , 'email' ,'cpf', 'phone']

    def __str__(self):
        return self.username

    objects = UserManager()

administrador/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Disciplina (models.Model):

    OPTATIVA = (
        ("S", "Sim"),
        ("N", "Não"),
    )
    
    STATUS = (
        ("Cursando", "Cursando"),
        ("Aprovado", "Aprovado"),
        ("Espera", "Espera")
    )
    
    nome = models.CharField(("Nome da Disciplina"), max_length=150, null=False)
    perido = models.IntegerField(("Periodo da disciplina"))
    carga_horaria = models.IntegerField(("Carga Horaria"))
    optativa = models.CharField(("Opitativa"), choices=OPTATIVA, blank=False, null=False,max_length=20)
    dependencia = models.ManyToManyField("self", verbose_name=("Dependencias"), blank=True, default='Sem Dependencia')
    aberto = models.BooleanField(("Aberto"), default='False')
    status = models.CharField('Status', choices=STATUS, max_length=20, default="Cursando")
    data_final = models.DateField(("Data Final"), blank=True, null=True,auto_now=False, auto_now_add=False)
    
    pedagogo = models.ForeignKey (User, verbose_name=("pedagogo"), on_delete=models.CASCADE, related_name='pedagogo', blank=True, null=True)
    banca_de_professores = models.ManyToManyField(User, verbose_name=("Banca de professores"), related_name='professores', blank=True, null=True)
    
    verbose_name = 'Disciplina'
    verbose_name_plural = 'Disciplinas'
    
    def __str__(self):
        return self.nome +' '+ str(self.perido) 
    
class Curso (models.Model):
    
    nome = models.CharField(("Nome do Curso"), max_length=150, null=False, blank=False)
    ano = models.DateField("Ano")
    periodos =  models.IntegerField(('Total de peridodos'), null=False, blank=False)
    #periodo_atual = models.IntegerField(('Total de peridodos'), null=True, blank=True)
    disciplina = models.ManyToManyField("administrador.Disciplina", verbose_name=("Disciplinas"),blank=False)
    
    coordenador = models.ForeignKey(User, verbose_name=("Coordenador"), on_delete=models.SET_NULL, null=True)
    
    
    verbose_name = 'Curso'
    verbose_name_plural = 'Cursos'
    
    def __str__(self):
        return self.nome +' ('+ str(self.ano.year) +')'
    

administrador/templates/CONFIG.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}
    <title>Aluno</title>
    <link rel="stylesheet" href="{% static 'css/CONFIG.css' %}">
{% endblock %}


{% block main %}
<div class="main">
    
    <p class="titulo">Dados do Aluno(a) - {{aluno.username}}</p>
<!--     <div class="erros">
        {{ form.errors }}
    </div> -->
    
    <div class="cadastro">
        <form action="" method="post" enctype='multipart/form-data'>
            {%csrf_token%}
            <div class="row_one">

                <div class="supossed_image">
                    <img src="{{ aluno.image.url }}" alt="">
                </div>
                <div class="row_image">
                    <p class="img_font" > Imagem Atual:</p> <a href="{{ aluno.image.url }}">{{ aluno.image.url }}</a>
                    Mudar:
                    <input type="file" name="image" accept="image/*" class="image" placeholder="Image" id="id_image">
                    
                </div>


                <div class="matricula_fix">
                    <p>Matricula</p>
                    {{form.matricula}}
                    <div  class="color_red">{{ form.matricula.errors }}</div>
                </div>
                
                
            </div>

            <div class="row_two">
                <div class="username_fix">
                    <p>Username</p>
                    {{ form.username }}
                </div>
                
                
            </div>

            <div class="row_three">
                <div  class="cpf_fix">
                    <p>CPF</p>
                    {{form.cpf}}
                    <div  class="color_red">{{ form.cpf.errors }}</div>
                </div>
                
                <div class="email_fix">
                    <p>Email</p>
                    {{form.email}}
                    <div  class="color_red">{{ form.email.errors }}</div>
                    
                </div>
                
                
            </div>

            <div class="row_four">
                <div class="data_fix">
                    <p>Data de nascimento</p>
                    {{form.data_de_nascimento}}
                    <div  class="color_red">{{ form.data_de_nascimento.errors }}</div>
                </div>
                

                <div class="telefone_fix">
                    <p>Telefone</p>
                    {{form.phone}}
                </div>
                
  
            </div>

            <div class="row_two">

                <div class="curso_fix">
                    <p>Curso</p>
                    <select name="curso_relacao" class="curso_relacao" placeholder="curso" readonly="readonly" id="id_curso_relacao">
                        
                        <option value="{{ aluno.curso_relacao.id }}" selected="">{{ aluno.curso_relacao.nome }}</option>
                                            
                      </select>

                </div>
                <div  class="color_red">{{ form.curso_relacao.errors }}</div>

            </div>

            <div class="alt">
                <div class="alterar_senha">
                    {% if grupo == "Aluno" %}
                        <a href="{% url 'student_change_password' %}">Alterar a Senha</a>
                    {% elif grupo == 'Professor' %}
                        <a href="{% url 'teacher_change_password' %}">Alterar a Senha</a>
                    {%  endif %}
                </div>
            </div>
            

            <div class="row_five">
                <button>
                    <input class="text_border" type="submit" id="input"value="Alterar Dados">
                </button>
            </div>
        </form>
        
{% endblock %}

administrador/templates/course.html
{% extends 'base.admin.html' %}
{% load static %}

{% block import_title_css %}
    <title>Aluno</title>
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
{% endblock %}


{% block main %}
   <!--  {{form.as_p}} -->
    <form action="" method="post" enctype='multipart/form-data'>
        {%csrf_token%}
        <!-- {{form.errors}} -->
        <div class="main">
            <p class="titulo">Curso - {{curso.nome}}</p>
        

            <div class="nome">
                <p>Nome</p>
                {{ form.nome }}
                <div  class="color_red">{{ form.nome.errors }}</div>
            </div>

            <div class="periodos">
                <p>Total de peridos</p>
                {{ form.periodos }}
                <div  class="color_red">{{ form.periodos.errors }}</div>
            </div>

            <div class="data">
                <p>Ano do Curso</p>
                {{ form.ano }}
                <div  class="color_red">{{ form.ano.errors }}</div>
            </div>

            <div class="diciplinas">
                <p>Disciplinas</p>
                {{ form.disciplina }}
                <div  class="color_red">{{ form.disciplina.errors }}</div>
            </div>

            <div class="coordenador">
                <p>Coordenador</p>
                <select name="coordenador" class="coordenador" placeholder="Coordenador do Curso" required="" id="id_coordenador">

                    {% for professor in grupo_professor %}

                        {% if professor.id == curso.coordenador.id %}
                            <option value="{{professor.id}}" selected>{{professor.username}}</option>
                        {% elif professor.curso_relacao == None %}
                            <option value="{{professor.id}}">{{professor.username}}</option>
                        {% endif %}
                        
                    {% endfor %}
                
                  </select>
                <div  class="color_red">{{ form.coordenador.errors }}</div>
            </div>

            <div class="submit">
                <button class="btn_submit"><input class="text_border" type="submit" id="input"value="Alterar Dados"></button>
            </div>
        </div>
    </form>
{% endblock %}

administrador/templates/sign_up_course.html
{% extends 'base.admin.html' %}
{% load static %}

{% block import_title_css %}
    <title>Cadastro Curso</title>
    <link rel="stylesheet" href="{% static 'css/sign_up_course.css' %}">
{% endblock %}

{% block main %}

<div class="main">
    
    <p class="title">Cadastro - Curso</p>
    <!-- {{ form.errors }} -->
    <form action="" method="post">
        
        {% csrf_token %}

        <div class="name_perido">
            <div>
                <p class="label_p">Nome</p>
                {{ form.nome }}
                <p class="color_red"> {{ form.nome.errors }} </p>
            </div>

            <div>
                <p class="label_p">Total de Peridodos</p>
                {{ form.periodos }}
                <p class="color_red"> {{ form.periodos.errors }} </p>
            </div>

        </div>

        <div class="dual_label">
            <div class="disciplina">
                <label for=""> {{ form.disciplina.label }} </label>
                {{ form.disciplina }}
                <p class="color_red"> {{ form.disciplina.errors }} </p>
            </div>

            <div>
            
                <div class="coordenador">
                    <label for="coordenador">{{ form.coordenador.label }}</label>

                    <select name="coordenador" class="coordenador" placeholder="Coordenador do Curso" required="" id="id_coordenador">
                        <option value="" selected="">---------</option>
                      
                        {% for teacher in prof%}
                            
                            {% if teacher.curso_relacao.nome == None %}
                                <option value="{{ teacher.id }}">{{ teacher.username }}</option>
                            {% endif %}
                        {% endfor %}
                      
                      </select>

                    <p class="color_red">{{ form.coordenador.errors }}</p>
                    <!-- {{ form.coordenador }} -->
                </div>
    
            </div>
            

        </div>
        <div class="name_perido_ano">
            
            <div class="disciplina">
                <p class="label_p">Ano</p>
                {{ form.ano }}
                <p class="color_red">{{ form.ano.errors }}</p>
            </div>

        </div>


        <div class="row_five">
            <button>
                <input type="submit" id="input"value="Cadastrar Curso">
            </button>
        </div>

    </form>

{% endblock %}

administrador/templates/sign_up_student.html
{% extends 'base.admin.html' %}
{% load static %}

{% block import_title_css %}
    <title>Cadastro Aluno</title>
    <link rel="stylesheet" href="{% static 'css/sign_up_student.css' %}">
{% endblock %}


{% block main %}
<div class="main">
    
    <p class="titulo">Cadastro de Aluno</p>
    <!-- {{ form.errors }} -->
    <div class="cadastro">
        <form action="" method="post" enctype='multipart/form-data'>
            {%csrf_token%}

            <div class="row_one">

                <div class="supossed_image">
                    <img id="blah" src="#" alt="your image" />
                </div>
                

                <div class="row_image">
                    <div>

                        

                        <input type="checkbox" id="ynimagem" name="ynimagem"> 
                        <label  class='label_checkbox'for="ynimagem">Não escolher uma foto</label>
                    </div>
                    <input type="file" name="image" accept="image/*" class="image" placeholder="Image" id="id_image">
                    <!-- {{form.image}} -->
                    <div style="width: 10px; height: 15px; overflow: hidden">{{form.matricula.errors}}</div>
                </div>
                <div>
                <div>
                    <p class="labels">Matricula</p>
                    {{form.matricula}}
                </div>
                <div class="text_red">{{form.matricula.errors}}</div>
                </div>
                
            </div>

            <div class="row_two">
                <div>
                    <p class="labels">Nome de usuario</p>
                    {{ form.username }}
                </div>
                
                <div class="text_red">{{form.username.errors}}</div>
                
            </div>

            <div class="row_three">

                <div> 
                    <div>
                        <p class="labels">CPF</p>
                        {{form.cpf}}
                    </div>
                    
                    <div class="text_red">{{form.cpf.errors}}</div>
                </div>

                <div>
                    <div>
                        <p class="labels">Email</p>
                        {{form.email}}
                    </div>
                    <div class="text_red">{{form.email.errors}}</div>
                </div>
                
                
            </div>

            <div class="row_four">

                <div>
                    <div>
                        <p class="labels">Data de nascimento</p>
                        {{form.data_de_nascimento}}
                    </div>
                    
                    <div class="text_red">{{form.data_de_nascimento.errors}}</div>
                </div>
                
                <div>
                    <div>
                        <p class="labels">Telefone</p>
                        {{form.phone}}
                    </div>
                    
                    <div class="text_red">{{form.phone.errors}}</div>
                </div>
                
  
            </div>

            <div class="row_four">
                <input style="visibility: hidden; position: absolute;" type="password" name="password1" autocomplete="new-password" class="password1" placeholder="Senha" required="" id="id_password1" value="{{senha}}">
                <input style="visibility: hidden; position: absolute;" type="password" name="password2" autocomplete="new-password" class="password2" placeholder="Confirme a Senha" required="" id="id_password2" value="{{senha}}">
<!--                 {{form.password1}}
                {{form.password2}} -->
  
            </div>

            <div class="row_two_">
                <div>
                    <p class="labels">Curso</p>
                    {{ form.curso_relacao }}
                </div>
                <div class="text_red">{{ form.curso_relacao.errors }}</div>
                
            </div>


            <div class="row_five">
                <button>
                    <label for="input"><img class="confia" src="{% static 'icons/out.svg'%}" alt=""></label>
                    <input type="submit" id="input"value="Cadastrar">
                </button>
            </div>
        </form>
        
{% endblock %}

{% block js%}
<script>

    document.getElementById('id_password1').value="{{senha}}"
    document.getElementById('id_password2').value="{{senha}}"

    id_image.onchange = evt => {
        const [file] = id_image.files
        if (file) {
          document.getElementById("blah").style.display = 'block';
          blah.src = URL.createObjectURL(file)
        }
      }

</script>

    

{% endblock %}

administrador/templates/sign_up_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}
    <title>Cadastro Professor</title>
    <link rel="stylesheet" href="{% static 'css/sign_up_student.css' %}">
{% endblock %}


{% block main %}
<div class="main">
    
    <p class="titulo">Cadastro de Professor
    </p>

    <div  class="erros">
        <!-- {{ form.errors }} -->
    </div>
    <div class="cadastro">
        <form action="" method="post" enctype='multipart/form-data'>
            {%csrf_token%}

            <div class="row_one">

                <div class="supossed_image">
                    <img id="blah" src="#" alt="your image" />
                </div>
                

                <div class="row_image">
                    <div>

                        

                        <input type="checkbox" id="ynimagem" name="ynimagem"> 
                        <label  class='label_checkbox'for="ynimagem">Não escolher uma foto</label>
                    </div>
                    {{form.image}}
                    <div style="width: 10px; height: 15px; overflow: hidden">{{form.matricula.errors}}</div>
                </div>
                <div>
                <div>
                    <p class="labels">Matricula</p>
                    {{form.matricula}}
                </div>
                <div class="text_red">{{form.matricula.errors}}</div>
                </div>
                
            </div>

            <div class="row_two">

                <div>
                    <p class="labels">Nome de usuario</p>
                    {{ form.username }}
                </div>
                
                <div class="text_red">{{form.username.errors}}</div>
                
            </div>

            <div class="row_three">

                <div> 
                    <div>
                        <p class="labels">CPF</p>
                        {{form.cpf}}
                    </div>
                    
                    <div class="text_red">{{form.cpf.errors}}</div>
                </div>

                <div>
                    <div>
                        <p class="labels">Email</p>
                        {{form.email}}
                    </div>
                    <div class="text_red">{{form.email.errors}}</div>
                </div>
                
            </div>

            <div class="row_four">

                <div>
                    <div>
                        <p class="labels">Data de nascimento</p>
                        {{form.data_de_nascimento}}
                    </div>
                    
                    <div class="text_red">{{form.data_de_nascimento.errors}}</div>
                </div>
                
                <div>
                    <div>
                        <p class="labels">Telefone</p>
                        {{form.phone}}
                    </div>
                    
                    <div class="text_red">{{form.phone.errors}}</div>
                </div>
  
            </div>

            <div class="row_four">

                <input style="visibility: hidden; position: absolute;" type="password" name="password1" autocomplete="new-password" class="password1" placeholder="Senha" required="" id="id_password1" value="{{senha}}">
                <input style="visibility: hidden; position: absolute;" type="password" name="password2" autocomplete="new-password" class="password2" placeholder="Confirme a Senha" required="" id="id_password2" value="{{senha}}">

                <!-- {{form.password1}}
                {{form.password2}} -->
  
            </div>

            <div class="row_two_">

                <div>
                    <p class="labels">Curso</p>
                    {{ form.curso_relacao }}
                </div>
                <div class="text_red">{{ form.curso_relacao.errors }}</div>

                <!-- <select style="pointer-events: none; touch-action: none " aria-readonly="readonly" name="curso_relacao" class="curso_relacao" placeholder="curso" id="id_curso_relacao" >

                  
                    <option selected value="3">Teste (2002)</option>
                  
                  </select> -->
                
            </div>  

            <div class="row_two_2">

                <div>
                    <p class="labels">Disciplina</p>
                    {{ form.disciplina_relacao }}
                </div>
                <div class="text_red">{{ form.disciplina_relacao.errors }}</div>

                
            </div>


            <div class="row_five">
                <button>
                    <label for="input"><img class="confia" src="{% static 'icons/out.svg'%}" alt=""></label>
                    <input type="submit" id="input"value="Cadastrar">
                </button>
            </div>
        </form>
        
{% endblock %}

{% block js%}
<script>

    document.getElementById('id_password1').value="{{senha}}"
    document.getElementById('id_password2').value="{{senha}}"

    id_image.onchange = evt => {
        const [file] = id_image.files
        if (file) {
          document.getElementById("blah").style.display = 'block';
          blah.src = URL.createObjectURL(file)
        }
      }

</script>
    

{% endblock %}

administrador/templates/student.html
{% extends 'base.admin.html' %}
{% load static %}

{% block import_title_css %}
    <title>Aluno</title>
    <link rel="stylesheet" href="{% static 'css/alter_student.css' %}">
{% endblock %}


{% block main %}
<div class="main">
    
    <p class="titulo">Dados do Aluno(a) - {{aluno.username}}</p>
    <div class="erros">
        {{ form.errors }}
    </div>
    
    <div class="cadastro">
        <form action="" method="post" enctype='multipart/form-data'>
            {%csrf_token%}
            <div class="row_one">

                <div class="supossed_image">
                    <img src="{{ aluno.image.url }}" alt="">
                </div>
                <div class="row_image">
                    Imagem Atual: <a href="{{ aluno.image.url }}">{{ aluno.image.url }}</a>
                    Mudar:
                    <input type="file" name="image" accept="image/*" class="image" placeholder="Image" id="id_image">
                    
                </div>


                <div class="matricula_fix">
                    <p>Matricula</p>
                    {{form.matricula}}
                </div>
                
                
            </div>

            <div class="row_two">
                <div class="username_fix">
                    <p>Username</p>
                    {{ form.username }}
                </div>
                
                
            </div>

            <div class="row_three">
                <div  class="cpf_fix">
                    <p>CPF</p>
                    {{form.cpf}}
                </div>
                
                <div class="email_fix">
                    <p>Email</p>
                    {{form.email}}
                </div>
                
                
            </div>

            <div class="row_four">
                <div class="data_fix">
                    <p>Data de nascimento</p>
                    {{form.data_de_nascimento}}
                </div>
                

                <div class="telefone_fix">
                    <p>telefone</p>
                    {{form.phone}}
                </div>
                
  
            </div>

            <div class="row_two">

                <div class="curso_fix">
                    <p>Curso</p>
                    {{ form.curso_relacao }}
                </div>     

            </div>


            <div class="row_five">
                <button>
                    <input class="text_border" type="submit" id="input"value="Alterar Dados">
                </button>
            </div>
        </form>
        
{% endblock %}

administrador/templates/teste.html
{% extends 'base.admin.html' %}
{% load static %}

{% block import_title_css %}
    <title>teste</title>
   <!--  <link rel="stylesheet" href="{% static 'css/home.css' %}"> -->
{% endblock %}



{% block main %}
    {% for cursos in curso %}
        {{ curso }}
    {% endfor %}
{% endblock %}