Aluno/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path
from .views import  home_aluno,\
                    aluno_curso,\
                    vizualizar_minhas_requisicoes_de_aproveitamento,\
                    vizualizar_minhas_requisicoes_de_certificacao,\
                    password_change,\
                    requisitar_aproveitamento_de_disciplina,\
                    requisitar_certificacao_de_conhecimento_class
                        


"""requisitar_aproveitamento_de_disciplina
requisitar_certificacao_de_conhecimento""" 

urlpatterns = [


    path('aluno_home/',  home_aluno, name = 'sweet_home'),
    path('aluno_home/alterar_senha/',  password_change.as_view(), name = 'student_change_password'),
    path('aluno_curso/<int:curso_id>', aluno_curso, name = 'curso_aluno'),
    
    #path('requisitar_aproveitamento_de_disciplina/<int:disciplina_id>', requisitar_aproveitamento_de_disciplina_class.as_view(), name='r_aproveitamento'),
    path('requisitar_aproveitamento_de_disciplina/<int:disciplina_id>',  requisitar_aproveitamento_de_disciplina, name='r_aproveitamento'),
    #path('requisitar_certificacao_de_conhecimento/<int:disciplina_id>',  requisitar_certificacao_de_conhecimento, name='r_certificacao'),
    path('requisitar_certificacao_de_conhecimento/<int:disciplina_id>',  requisitar_certificacao_de_conhecimento_class.as_view(), name='r_certificacao'),
    
    path('aluno_requisicoes/aproveitamento/', vizualizar_minhas_requisicoes_de_aproveitamento, name='aluno_requisicoes_de_aproveitamento'),
    path('aluno_requisicoes/certificacao/', vizualizar_minhas_requisicoes_de_certificacao, name='aluno_requisicoes_de_certificacao')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GCA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrador.urls')),
    path('Aluno/', include('Aluno.urls')),
    path('Coordenador/', include('coordenador.urls')),
    path('user/', include('Users.urls')),
    path('user/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aluno/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.

class Aproveitamento_de_disciplina (models.Model):
    
    STATUS = (
        ("aprovado", "Aprovado"),
        ("reprovado", "Reprovado"),
        ("aguardo", "Aguardo")
    )

    disciplina =  models.ForeignKey('administrador.Disciplina', on_delete=models.CASCADE)
    motivo = models.CharField("Motivo", max_length=250, blank=True, null=True)
    
    historico = models.FileField(("Historico"), upload_to='documentos', max_length=1000)
    ementa = models.FileField(("Ementa antiga escola"), upload_to='documentos', max_length=1000)
    ementa_atual = models.FileField(("Ementa nova escola"), upload_to='documentos', max_length=1000)
    comprovante = models.FileField(("Comprovante"), upload_to='documentos', max_length=1000, blank=True, null=True)
    
    status_requisição = models.CharField(("Status"), choices=STATUS, blank=False, null=False, max_length=20,  default='reprovado')
    requisitor =  models.ForeignKey(User, verbose_name=("Requisitor"), on_delete=models.CASCADE, blank=False, null=False)
 
    verbose_name = 'Aproveitamento de disciplina'
    verbose_name_plural = 'Aproveitamentos de disciplina'
    
    class Meta:
      db_table = 'Aluno_aproveitamento_de_disciplina'
      unique_together = (('disciplina', 'requisitor'),)
    
    def __str__(self):
        return self.disciplina.nome +' '+ self.requisitor.username
    
    
    
class Certificação_de_conhecimento (models.Model):
    
    STATUS = (
        ("aprovado", "Aprovado"),
        ("reprovado", "Reprovado"),
        ("aguardo", "Aguardo")
    )

    disciplina =  models.ForeignKey('administrador.Disciplina', on_delete=models.CASCADE)
    status_requisição = models.CharField(("Status"), choices=STATUS, blank=False, null=False, max_length=20,  default='reprovado')
    nota = models.FloatField(("Nota"), blank=True, null=True, default=0)
    requisitor =  models.ForeignKey(User, verbose_name=("Requisitor"), on_delete=models.CASCADE, blank=False, null=False)

    verbose_name = 'Certificação de conhecimento'
    verbose_name_plural = 'Certificações de conhecimento'
    
    class Meta:
      db_table = 'Aluno_certificação_de_conhecimento'
      unique_together = (('requisitor', 'disciplina'),)
    
    def __str__(self):
        return self.disciplina.nome +' '+ self.requisitor.username
    
    

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.db.models import signals

# Create your models here.

class UserManager(BaseUserManager):
    #REQUIRED_FIELDS = ['matricula','username' , 'email' ,'cpf', 'phone']

    def _create_user(self, image,  matricula, username, email, cpf,  phone, data_de_nascimento, disciplina_relacao, password, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        if not matricula:
           raise ValueError("O matricula é obrigatório")
        if not username:
           raise ValueError("O username é obrigatório")
        if not cpf:
           raise ValueError("O cpf é obrigatório")
        if not phone:
            raise ValueError("O phone é obrigatório")
        
        email = self.normalize_email(email)
        
        """ username = seusername
        matricula = seemail """
        
        user = self.model(image=image, matricula=matricula, username=username, email=email, cpf=cpf, phone=phone, data_de_nascimento=data_de_nascimento, disciplina_relacao=disciplina_relacao, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def _create_super_user(self,  matricula, username, email, cpf,  phone, password, **extra_fields):
        if not email:
            raise ValueError("O e-mail é obrigatório")
        if not matricula:
           raise ValueError("O matricula é obrigatório")
        if not username:
           raise ValueError("O username é obrigatório")
        if not cpf:
           raise ValueError("O cpf é obrigatório")
        if not phone:
            raise ValueError("O phone é obrigatório")
        
        email = self.normalize_email(email)
        
        """ username = seusername
        matricula = seemail """
        
        user = self.model(matricula=matricula, username=username, email=email, cpf=cpf, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, image, matricula, username, email, cpf,  phone, data_de_nascimento=None, disciplina_relacao=None,password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', True)
        return self._create_user( image, matricula, username, email, cpf,  phone, data_de_nascimento, disciplina_relacao, password, **extra_fields)

    def create_superuser(self, matricula, username, email, cpf, phone, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser precisa ter is_superuser = True')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser precisa ter is_staff = True')

        return self._create_super_user( matricula, username, email, cpf,  phone, password, **extra_fields)



class CustomUser(AbstractUser):


    image = models.ImageField(upload_to='Media', blank=True, null=False, default='Media/no_image_dafaut.jpg')
    matricula = models.CharField("Matricula", max_length=150, unique=True)
    username = models.CharField(("Nome"), max_length=50, unique=False, primary_key=None)
    email = models.EmailField("E-mail", unique=True)
    cpf = models.CharField("CPF", max_length=14, unique=True)
    phone = models.CharField("Telefone", max_length=15, blank=True, null=True)
    data_de_nascimento = models.DateField('Data de Nascimento', blank=True, null=True)
    primeiro_login = models.BooleanField(default=True)
    
    
    curso_relacao = models.ForeignKey("administrador.Curso", verbose_name=("Curso"), blank=True, null=True,on_delete=models.SET_NULL)
    disciplina_relacao = models.ManyToManyField("administrador.Disciplina", verbose_name=("Disciplina"), blank=True)
    
    disciplina_concluidas = models.ManyToManyField("administrador.Disciplina", related_name='Disciplina_cluidas', verbose_name=("Disciplina Concluidas"), blank=True)
    
    is_staff = models.BooleanField('Membro da equipe', default=True)

    USERNAME_FIELD = 'matricula'
    REQUIRED_FIELDS = ['username' , 'email' ,'cpf', 'phone']

    def __str__(self):
        return self.username

    objects = UserManager()

Aluno/templates/home_student.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}
<link rel="stylesheet" href="{% static 'css/home_student.css' %}">

<title>Home - Alunos</title>
{% endblock %}

{% block main %}

<div class="main">

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li><p>{{ message }}</p></li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="title">
        <h1> Bem-vindo {{ username }}</h1>
    </div>

    {% if curso == None %}

        <div class="curso">

            <div class="white_bar">
                <p>Você não está cadastrado(a) em nem um curso, entre em contato com um administrador</p>
            </div>

        </div>

    {% elif curso != None %}

        <div class="curso">
            
            <div class="white_bar" id="teste">
                <p>{{curso}}</p>
            </div>

            <a class="link_clear" href="{% url 'curso_aluno' aluno_dados.curso_relacao.id %}">
                <div class="visualizar" id="visualizar">
                    <p>Visualizar Dados</p>
                </div>
            </a>

        </div>

        <p class="requisicoes_title">Minhas Requisições</p>

        <div class="aproveitamento_certificacao">


            <div class="aproveitamento">
                <p class="texto_requisicoes">Aproveitamento de Disciplina</p>
                
                <a class="link_clear" href="{% url 'aluno_requisicoes_de_aproveitamento' %}">
                    <div class="visualizar">
                        <p>Visualizar</p>
                    </div> 
                </a>
                
            </div>
            
            <div class="certificacao">
                <p class="texto_requisicoes">Certificação de Conhecimento</p>

                <a class="link_clear" href="{% url 'aluno_requisicoes_de_certificacao' %}">
                    <div class="visualizar">
                        <p>Visualizar</p>
                    </div> 
                </a>
                
            </div>

        </div>
        
    {% endif %}
    
</div>
{% endblock %}

Aluno/templates/requisitar_aproveitamento_de_disciplina.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/requisitar_aproveitamento.css' %}">
<title>Requisitar Aproveitamento de Disciplina</title>

{% endblock %}

{% block main %}
<div class="main">
    <form  action="" method="post"  enctype='multipart/form-data'>
        {%csrf_token%}
        <!-- {{form.as_p}} -->
    </form>
    <p class="titulo">Requisitar Aproveitamento de Disciplina {{ object.username }}</p>
    <div style="color: red;">{{ form.errors }}</div>

    <form action="" method="post"  enctype='multipart/form-data'>
        {%csrf_token%}
   
        <div class="content">

            <div class="diciplina">
                <p class="titulo_2">Disciplina</p>


               <!--  {{form.disciplina}} -->

                <select name="disciplina" class="disciplina" placeholder="curso" id="id_curso_relacao" style="pointer-events: none; touch-action: none; width: 745px; background-color:  #c1c1c1;" aria-readonly="readonly"  >
                
                    <option selected value="{{disciplina_requisição.id}}">{{disciplina_requisição.nome}}</option>

                </select>

            </div>


            <div class="motivo">
                <p class="titulo_2">Motivo</p>
                {{form.motivo}}
            </div>

            <div class="documentos">

                <p class="titulo_2">Documentos</p>

                <div class="historico">
                    <p class="titulo_2">Historico</p>
                    {{form.historico}}
                </div>

                <div class="comprovante">
                    <p class="titulo_2">Emanta Atual</p>
                    {{form.ementa}}
                </div>

                <div class="comprovante">
                    <p class="titulo_2">Emanta Passada</p>
                    {{form.ementa_atual}}
                </div>

                <div class="comprovante">
                    <p class="titulo_2">Comprovante</p>
                    {{form.comprovante}}
                </div>
            </div>

            <div class="requisitor" >
                <select name="requisitor" id="id_requisitor" style="visibility: hidden;">
                    <option value="{{user.id}}">{{user.username}}</option>
                </select>
            </div>

            <div class="requisitor"  >
                <select name="status_requisição" id="id_status_requisição" style="visibility: hidden;">
                    <option value="aguardo">Aguardo</option>
                </select>
            </div>

        </div>

        <div class="submit_div">
            <button class="submit">
                Enviar Requisição
            </button>
        </div>

    </form>
    
    
</div>

{% endblock %}

Aluno/templates/requisitar_certificação_de_conhecimento.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/requisitar_certificacao.css' %}">
<title>Requisitar Certificação de Conhecimento</title>

{% endblock %}

{% block main %}

<!-- <form action="">
    {{form.as_p}}
</form> -->
<div class="main">
    <form action="" method="post">
        {%csrf_token%}
        <p class="titulo">Certificação de Conhecimento</p>
        <div style="color: red;">{{ form.errors }}
        </div>

        <div class="content">
            <div >
                <p class="color_white">{{form.disciplina.label}}</p>
                <!-- {{form.disciplina}} -->
                
                <select name="disciplina" class="disciplina" placeholder="curso" id="id_curso_relacao" aria-readonly="readonly"  >
                
                    <option selected value="{{disciplina.id}}">{{disciplina.nome}}</option>

                </select>


            </div>

            <div class="requisitor_div" >
                <select name="requisitor" id="id_requisitor" style="visibility: hidden; position:absolute">
                    <option value="{{user.id}}">{{user.username}}</option>
                </select>
            </div>

            <div class="status_requisição_div"  >
                <select name="status_requisição" id="id_status_requisição" style="visibility: hidden; position:absolute">
                    <option value="aguardo">Aguardo</option>
                </select>
            </div>


        </div>

        <div class="submit_div">
            <button class="submit">
                Enviar Requisição
            </button>
        </div>
    </form>

</div>
{% endblock %}

Aluno/templates/vizualizar_dados.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/vizualizar_aluno_curso.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/__modal_selecionarAC.css' %}">
<title>Dados do Curso</title>

{% endblock %}

{% block main %}

    <div class="main">

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li><p>{{ message }}</p></li>
                {% endfor %}
            </ul>
        {% endif %}
        


        <div class="curso">
            <p class="titulo_curso">Curso</p>

            <div class="dados_curso">
                <p>Nome: {{curso}}<br>
                Periodos: {{curso.periodos}}<br>
                Total de disciplinas {{ total_disciplinas }}: {{total_de_optativas}} Obrigatoria | {{total_de_nao_optativas}}  Optativa </p>
            </div>
        </div>

        <div class="disciplinas">
            <p class="titulo_disciplina">Disciplinas</p>

            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nome</th>
                      <th scope="col">Periodo</th>
                      <th scope="col">Status</th>
                      <th scope="col">Carga Horaria</th>
                      <th scope="col">-</th>
                    </tr>
                </thead>

                <tbody>
                    {% for disciplina in disciplinas %}
                    <div class="modal fade" id="exampleModal{{disciplina.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div id="modal_mine">
                                    <div class="modal_selecionar">
                                        <div class="aproveitamento">
                                            <a href="{% url 'r_aproveitamento' disciplina.id %}"><p>Requisitar<br>Aproveitamento de<br>disciplina</p></a>
                                        </div>
                                        <div class="conhecimento">
                                            <a href="{% url 'r_certificacao' disciplina.id %}"><p>Requisitar<br>Certificação de<br>conhecimento</p></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div>
                    </div>
                    
                        <tr>
                            <th scope="row"> {{disciplina.id}} </th>
                            <td>{{disciplina.nome}}</td>
                            <td>{{disciplina.perido}}</td>
                            {% if not user.disciplina_concluidas.all%}
                                <td><!-- {{disciplina.status}} --> Cursando</td>
                            {% else %}
                                {% for disciplina_concluida in user.disciplina_concluidas.all%}
                                    {% if disciplina_concluida == disciplina%}
                                        <td><!-- {{disciplina.status}} --> Cursada</td>  
                                    {% else %}   
                                        <td><!-- {{disciplina.status}} --> Cursando</td>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                            <td>{{disciplina.carga_horaria}}</td>
                            <td>

                                <button type="button" class="" data-bs-toggle="modal" data-bs-target="#exampleModal{{disciplina.id}}">
                                    Opções
                                </button>
                        
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}
{% block js%}
<!-- <script>
    function show_modal ()
    {
        var modal = document.getElementById('modal_mine')
        var teste = document.getElementById('teste')
        
       
        modal.classList.toggle('hidden');


        modal.style.opacity =  '1.0';
        var x = 0
        var y = 1

        modal.style.display = "flex";

        teste.onclick = function() 
        {
            x = 1
            console.log(x)
            y = 2
        }
        
        
        modal.onclick = function() 
        {
            x = 2
            console.log(x)

            if (y == 2)
            {
                console.log('n modal')
            }
            else if ( y == 1)
            {
                modal.style.display = "none";
                
            }
            y= 1
        }
        
       
        console.log(x)
        
    }
    
</script> -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
{% endblock %}

Aluno/templates/vizualizar_minhas_requisicoes_aproveitamento.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/vizualizar_aluno_curso.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/__modal_selecionarAC.css' %}">
<title>Lista de requisições de aproveitamento de disciplina</title>

{% endblock %}

{% block main %}

    <div class="main">
        
        <div class="curso">
            <p class="titulo_curso">Curso</p>

            <div class="dados_curso">
                <p>Nome: {{curso}}<br>
                Periodos: {{curso.periodos}}<br>
                Total de disciplinas {{ total_disciplinas }}: {{total_de_optativas}} Obrigatoria | {{total_de_nao_optativas}}  Optativa </p>
            </div>
        </div>

        <div class="disciplinas">
            <p class="titulo_disciplina">Requições de Aproveitamento de disciplina: {{total_requisicoes_aproveitamento}}</p>

            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nome</th>
                      <th scope="col">Periodo</th>
                      <th scope="col">Optativa</th>
                      <th scope="col">Status</th>
                    </tr>
                </thead>

                <tbody>
                    {% for requisicoes in requisicoes_de_aproveitamento %}

                        {% if requisicoes.status_requisição == 'reprovado' %}
                            <tr class="reprovado">
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Reprovado</td>
                            </tr>
                        {% elif requisicoes.status_requisição == 'aprovado' %}
                            <tr class="aprovado">
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Aprovado</td>
                            </tr>
                        {% else %}
                            <tr>
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Aguardo</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}
{% block js%}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
{% endblock %}

Aluno/templates/vizualizar_minhas_requisicoes_certificacao.html
{% extends 'base.html' %}
{% load static %}

{% block import_title_css %}

<link rel="stylesheet" href="{% static 'css/vizualizar_aluno_curso.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/__modal_selecionarAC.css' %}">
<title>Lista de requisições de certificacao de conhecimento</title>

{% endblock %}

{% block main %}

    <div class="main">
        
        <div class="curso">
            <p class="titulo_curso">Curso</p>

            <div class="dados_curso">
                <p>Nome: {{curso}}<br>
                Periodos: {{curso.periodos}}<br>
                Total de disciplinas {{ total_disciplinas }}: {{total_de_optativas}} Obrigatoria | {{total_de_nao_optativas}}  Optativa </p>
            </div>
        </div>

        <div class="disciplinas">
            <p class="titulo_disciplina">Requições de certificacao de conhecimento: {{total_requisicoes_certificacao}}</p>

            <table class="table">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Nome</th>
                      <th scope="col">Periodo</th>
                      <th scope="col">Optativa</th>
                      <th scope="col">Status</th>
                    </tr>
                </thead>

                <tbody>
                    {% for requisicoes in requisicoes_de_certificacao %}

                        {% if requisicoes.status_requisição == 'reprovado' %}
                            <tr class="reprovado">
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Reprovado</td>
                            </tr>
                        {% elif requisicoes.status_requisição == 'aprovado' %}
                            <tr class="aprovado">
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Aprovado</td>
                            </tr>
                        {% else %}
                            <tr>
                                <th scope="row"> {{requisicoes.id}} </th>
                                <td>{{requisicoes.disciplina.nome}}</td>
                                <td>{{requisicoes.disciplina.perido}}</td>
                                <td>{{requisicoes.disciplina.optativa}}</td>
                                <td><!-- {{requisicoes.status_requisição}} -->Aguardo</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}
{% block js%}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
{% endblock %}